name: app_ui
description: App UI Component Library
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  mockingjay: ^0.3.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0
  custom_lint: ^0.2.0
  a_lint:
    path: ../../../packages/a_lint
  b_lint:
    path: ../../../packages/b_lint
  c_lint:
    path: ../../../packages/c_lint
  d_lint:
    path: ../../../packages/d_lint
  e_lint:
    path: ../../../packages/e_lint
  f_lint:
    path: ../../../packages/f_lint
  g_lint:
    path: ../../../packages/g_lint
  h_lint:
    path: ../../../packages/h_lint
  i_lint:
    path: ../../../packages/i_lint
  j_lint:
    path: ../../../packages/j_lint
  k_lint:
    path: ../../../packages/k_lint
  l_lint:
    path: ../../../packages/l_lint
  m_lint:
    path: ../../../packages/m_lint
  n_lint:
    path: ../../../packages/n_lint
  o_lint:
    path: ../../../packages/o_lint
  p_lint:
    path: ../../../packages/p_lint
  q_lint:
    path: ../../../packages/q_lint
  r_lint:
    path: ../../../packages/r_lint
  s_lint:
    path: ../../../packages/s_lint
  t_lint:
    path: ../../../packages/t_lint
  u_lint:
    path: ../../../packages/u_lint
  v_lint:
    path: ../../../packages/v_lint
  w_lint:
    path: ../../../packages/w_lint
  x_lint:
    path: ../../../packages/x_lint
  y_lint:
    path: ../../../packages/y_lint

dependency_overrides:
  custom_lint: ^0.2.0
  custom_lint_builder: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSerif-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSerif-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSerif-Regular.ttf
          weight: 400
    - family: NotoSansDisplay
      fonts:
        - asset: assets/fonts/NotoSansDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansDisplay-SemiBold.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
