name: news_blocks_ui
description: A Flutter package that contains UI components for news blocks.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_ui:
    path: ../app_ui
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  google_mobile_ads: ^2.0.0
  news_blocks:
    path: ../../api/packages/news_blocks
  path_provider_platform_interface: ^2.0.5
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.3
  url_launcher: ^6.1.7
  url_launcher_platform_interface: ^2.1.1
  video_player: ^2.4.2
  video_player_platform_interface: ^5.1.4

dev_dependencies:
  fake_async: ^1.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^4.0.0
  custom_lint: ^0.2.0
  a_lint:
    path: ../../../packages/a_lint
  b_lint:
    path: ../../../packages/b_lint
  c_lint:
    path: ../../../packages/c_lint
  d_lint:
    path: ../../../packages/d_lint
  e_lint:
    path: ../../../packages/e_lint
  f_lint:
    path: ../../../packages/f_lint
  g_lint:
    path: ../../../packages/g_lint
  h_lint:
    path: ../../../packages/h_lint
  i_lint:
    path: ../../../packages/i_lint
  j_lint:
    path: ../../../packages/j_lint
  k_lint:
    path: ../../../packages/k_lint
  l_lint:
    path: ../../../packages/l_lint
  m_lint:
    path: ../../../packages/m_lint
  n_lint:
    path: ../../../packages/n_lint
  o_lint:
    path: ../../../packages/o_lint
  p_lint:
    path: ../../../packages/p_lint
  q_lint:
    path: ../../../packages/q_lint
  r_lint:
    path: ../../../packages/r_lint
  s_lint:
    path: ../../../packages/s_lint
  t_lint:
    path: ../../../packages/t_lint
  u_lint:
    path: ../../../packages/u_lint
  v_lint:
    path: ../../../packages/v_lint
  w_lint:
    path: ../../../packages/w_lint
  x_lint:
    path: ../../../packages/x_lint
  y_lint:
    path: ../../../packages/y_lint

dependency_overrides:
  custom_lint: ^0.2.0
  custom_lint_builder: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  assets:
    package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
