name: sample
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.5

dependencies:
  archive: ^3.4.8
  path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
