name: sample
description: A sample that shows custom_lint strict versioning issue.
publish_to: "none"

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  special_widget:
    path: packages/special_widget

dev_dependencies:
  custom_lint: ^0.2.12
  a_lint:
    path: ../packages/a_lint
  bloc: 8.1.0
