name: coverage

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 👀 View Coverage
        run: cat coverage/lcov.info

      - name: 📊 Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          path: coverage/lcov.info
