name: sample_coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample
    steps:
      - uses: actions/checkout@v2
      - name: Check for test files
        id: test_file_check
        run: echo "result=false" >> $GITHUB_OUTPUT
      - name: Very Good Coverage
        if: steps.test_file_check.outputs.result == 'true'
        run: echo "hello world"
