name: sample_coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    if: ls sample/test == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample
    steps:
      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 100
