name: sample_coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sample
    steps:
      - name: Check for test files
        id: test_file_check
        run: echo "result=false" >> $GITHUB_OUTPUT
      - name: Very Good Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 100
