name: sample_coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    if: ls sample/test == 'octo-org/octo-repo-prod'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample
    steps:
      - name: Check for test files
        shell: bash
        id: test_file_check
        run: |
          if [ "$(ls -A sample/test)" ]; then
              echo "result=true"
          else
              echo "result=false"
          fi
      - uses: VeryGoodOpenSource/very_good_coverage@v2
        if: steps.test_file_check.outputs.result == 'true'
        with:
          path: "./coverage/lcov.info"
          min_coverage: 100
